/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  PC04
 * Created: 22-abr-2019
 */

CREATE TABLE AUTOR (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    TELEFONO VARCHAR (100),
    PAIS VARCHAR(30),
    PROVINCIA VARCHAR(40),
    LOCALIDAD VARCHAR(50),
    APARTADO_CORREOS VARCHAR(500),
    CODIGO_POST VARCHAR (100),
    FECHA_NACIMIENTO DATE,
    FOTO VARCHAR(500),
    CONSTRAINT ID_AUTOR_PK PRIMARY KEY (ID)
);

CREATE TABLE LIBRO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(60) NOT NULL,
    NºPAGINAS INT,
    AUTOR INTEGER,
    EDITORIAL VARCHAR(60),
    IDIOMA VARCHAR(40),
    ENCUADERNACION VARCHAR(60),
    ISBN VARCHAR (100) NOT NULL,
    AÑO_EDICION DATE,
    PAIS_DE_EDICION VARCHAR(50),
    PRECIO DECIMAL(8,2),
    EN_ESTOCK BOOLEAN,
    FOTO VARCHAR(500),
    DESCRIPCION VARCHAR(3200),
    CONSTRAINT ID_LIBRO_PK PRIMARY KEY (ID),
    CONSTRAINT AUTOR_LIBRO_FK FOREIGN KEY (AUTOR) REFERENCES AUTOR (ID)
);